name: CI/CD Angular & Spring Boot v0.911

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:


      - name: Build the Docker image for the backend
        uses: actions/checkout@v4
        # Backend build & test
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'
      # Backend
      - name: Build & test Spring Boot
        run: |
          cd back
          ./mvnw clean verify

      - name: Upload backend (Jacoco) coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: back/target/site/jacoco/jacoco.xml
          flags: backend
          name: backend-coverage
      - name: Move backend coverage to GitHub Pages dir
        run: |
          mkdir -p coverage/backend
          cp -r back/target/site/jacoco/* coverage/backend/
      - name: Upload backend coverage to GitHub Pages (main branch)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage/backend
          destination_dir: coverage/backend
          keep_files: true
          publish_branch: gh-pages

      # Frontend
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install & build Angular
        run: |
          cd front
          npm ci
          npm run build
          npm run test -- --code-coverage --watch=false --browsers=ChromeHeadlessCI

      - name: Upload frontend (Angular) coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: front/coverage/bobapp/lcov.info
          flags: frontend
          name: angular-coverage
      - name: Move frontend coverage to GitHub Pages dir
        run: |
          mkdir -p coverage/frontend
          cp -r front/coverage/bobapp/* coverage/frontend/
      - name: Upload frontend coverage to GitHub Pages (main branch)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage/frontend
          destination_dir: coverage/frontend
          keep_files: true
          publish_branch: gh-pages



