name: CI/CD Angular & Spring Boot v0.4

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:


      - name: Build the Docker image for the backend
        uses: actions/checkout@v4
        # Backend build & test
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'
      - name: Build & test Spring Boot
        run: |
          cd back
          ./mvnw clean verify
      # Frontend build & test
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
            node-version: '18'
      - name: Install & build Angular
        run: |
            cd front
            npm ci
            npm run build
            npm test -- --watch=false