name: CI/CD Angular & Spring Boot for Bob APP v0.93

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:


      - name: Build the Docker image for the backend
        uses: actions/checkout@v4
        # Backend build & test
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
      - name: Build & test Spring Boot
        run: |
          cd back
          ./mvnw clean verify

      - name: SonarQube Scan - Backend
        run: |
          cd back
          ./mvnw org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Frontend
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install & build Angular
        run: |
          cd front
          npm ci
          npm run build
          npm run test:ci

      - name: SonarQube Scan - Frontend
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: front
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


