name: CI/CD Angular & Spring Boot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:


      - name: Build the Docker image for the backend
        uses: actions/checkout@v4
        # Backend build & test
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'
      - name: Build & test Spring Boot
        run: |
          cd backend
          ./mvnw clean verify