name: CI/CD Angular & Spring Boot for Bob APP v0.94

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:


      - name: clone the source code for the backend
        uses: actions/checkout@v4
        # Backend build & test
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
      - name: Build & test Spring Boot
        run: |
          cd back
          ./mvnw clean verify
      - name: Test Reporting
        uses: phoenix-actions/test-reporting@v15
        if: always()  # Run this step even if previous steps fail
        with:
          name: backend tests
          path: back/target/surefire-reports/*.xml
          reporter: java-junit

      - name: SonarQube Scan - Backend
        run: |
          cd back
          ./mvnw org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Build Docker image
        run: |
          docker build -t aflouat/bobapp-back:latest -f back/Dockerfile back

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker tag aflouat/bobapp-back:latest aflouat/bobapp-back:${{ github.sha }}
          docker push aflouat/bobapp-back:${{ github.sha }}
          docker push aflouat/bobapp-back:latest
      # Frontend
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install & build Angular
        run: |
          cd front
          npm ci
          npm run build
          npm run test:ci

      - name: SonarQube Scan - Frontend
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: front
          args: >
            -Dsonar.projectKey=aflouat-bobapp-front
            -Dsonar.organization=aflouat
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=src
            -Dsonar.exclusions=node_modules/**,dist/**
            -Dsonar.tests=src
            -Dsonar.test.inclusions=**/*.spec.ts
            -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


