name: CI/CD Angular & Spring Boot v0.911

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:


      - name: Build the Docker image for the backend
        uses: actions/checkout@v4
        # Backend build & test
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'
      # Backend
      - name: Build & test Spring Boot
        run: |
          cd back
          ./mvnw clean verify
      # Test report
      - name: Test Report
        uses: phoenix-actions/test-reporting@v8
        id: test-report               # Set ID reference for step
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: reports/jest-*.xml    # Path to test results
          reporter: jest-junit        # Format of test results

      # Frontend
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install & build Angular
        run: |
          cd front
          npm ci
          npm run build
          npm run test -- --code-coverage --watch=false --browsers=ChromeHeadlessCI

      - name: Test Report
          uses: phoenix-actions/test-reporting@v8
          id: test-report               # Set ID reference for step
          if: success() || failure()    # run this step even if previous step failed
          with:
            name: JEST Tests            # Name of the check run which will be created
            path: reports/jest-*.xml    # Path to test results
            reporter: jest-junit        # Format of test results


